# Generated by Django 3.2.8 on 2021-10-16 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masjid1', '0001_initial_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monthly_Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('month', models.DateField()),
                ('fee', models.IntegerField()),
                ('discounted', models.BooleanField(default=False)),
                ('roll_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masjid1.student_registration')),
            ],
            options={
                'db_table': 'fee_record',
            },
        ),
    ]
