# Generated by Django 3.2.8 on 2021-10-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masjid1', '0002_monthly_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_income', models.IntegerField()),
                ('total_expense', models.IntegerField()),
                ('remaining', models.IntegerField()),
            ],
            options={
                'db_table': 'account_record',
            },
        ),
    ]
